[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "node_modules"]
fs_permissions = [{ access = "read-write", path = "./"}]
via_ir = true
solc_version = "0.8.30"

[rpc_endpoints]
base = "https://mainnet.base.org"
baseSepolia = "https://sepolia.base.org"
localhost = "http://127.0.0.1:8545"

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }
baseSepolia = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
bracket_spacing = true
