/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  84532: {
    // GroupPoolFactory: {
    //   address: "0x6379ebd504941f50d5bfde9348b37593bd29c835",
    //   abi: [
    //     {
    //       type: "constructor",
    //       inputs: [],
    //       stateMutability: "nonpayable"
    //     },
    //     {
    //       type: "function",
    //       name: "UPGRADE_INTERFACE_VERSION",
    //       inputs: [],
    //       outputs: [
    //         {
    //           name: "",
    //           type: "string",
    //           internalType: "string"
    //         }
    //       ],
    //       stateMutability: "view"
    //     },
    //     {
    //       type: "function",
    //       name: "createdAt",
    //       inputs: [],
    //       outputs: [
    //         {
    //           name: "",
    //           type: "uint256",
    //           internalType: "uint256"
    //         }
    //       ],
    //       stateMutability: "view"
    //     },
    //     {
    //       type: "function",
    //       name: "deposit",
    //       inputs: [
    //         {
    //           name: "_amount",
    //           type: "uint256",
    //           internalType: "uint256"
    //         }
    //       ],
    //       outputs: [],
    //       stateMutability: "nonpayable"
    //     },
    //     {
    //       type: "function",
    //       name: "deposit",
    //       inputs: [
    //         {
    //           name: "_amount",
    //           type: "uint256",
    //           internalType: "uint256"
    //         },
    //         {
    //           name: "_cid",
    //           type: "string",
    //           internalType: "string"
    //         }
    //       ],
    //       outputs: [],
    //       stateMutability: "nonpayable"
    //     },
    //     {
    //       type: "function",
    //       name: "depositCids",
    //       inputs: [
    //         {
    //           name: "",
    //           type: "uint256",
    //           internalType: "uint256"
    //         }
    //       ],
    //       outputs: [
    //         {
    //           name: "",
    //           type: "string",
    //           internalType: "string"
    //         }
    //       ],
    //       stateMutability: "view"
    //     },
    //     {
    //       type: "function",
    //       name: "depositCount",
    //       inputs: [],
    //       outputs: [
    //         {
    //           name: "",
    //           type: "uint256",
    //           internalType: "uint256"
    //         }
    //       ],
    //       stateMutability: "view"
    //     },
    //     {
    //       type: "function",
    //       name: "getBalance",
    //       inputs: [],
    //       outputs: [
    //         {
    //           name: "",
    //           type: "uint256",
    //           internalType: "uint256"
    //         }
    //       ],
    //       stateMutability: "view"
    //     },
    //     {
    //       type: "function",
    //       name: "getCid",
    //       inputs: [
    //         {
    //           name: "_depositId",
    //           type: "uint256",
    //           internalType: "uint256"
    //         }
    //       ],
    //       outputs: [
    //         {
    //           name: "",
    //           type: "string",
    //           internalType: "string"
    //         }
    //       ],
    //       stateMutability: "view"
    //     },
    //     {
    //       type: "function",
    //       name: "getDepositCount",
    //       inputs: [],
    //       outputs: [
    //         {
    //           name: "",
    //           type: "uint256",
    //           internalType: "uint256"
    //         }
    //       ],
    //       stateMutability: "view"
    //     },
    //     {
    //       type: "function",
    //       name: "getLockEndTime",
    //       inputs: [],
    //       outputs: [
    //         {
    //           name: "",
    //           type: "uint256",
    //           internalType: "uint256"
    //         }
    //       ],
    //       stateMutability: "view"
    //     },
    //     {
    //       type: "function",
    //       name: "initialize",
    //       inputs: [
    //         {
    //           name: "_owner",
    //           type: "address",
    //           internalType: "address"
    //         },
    //         {
    //           name: "_lockDuration",
    //           type: "uint256",
    //           internalType: "uint256"
    //         },
    //         {
    //           name: "_usdc",
    //           type: "address",
    //           internalType: "address"
    //         },
    //         {
    //           name: "_vaultName",
    //           type: "string",
    //           internalType: "string"
    //         }
    //       ],
    //       outputs: [],
    //       stateMutability: "nonpayable"
    //     },
    //     {
    //       type: "function",
    //       name: "isMature",
    //       inputs: [],
    //       outputs: [
    //         {
    //           name: "",
    //           type: "bool",
    //           internalType: "bool"
    //         }
    //       ],
    //       stateMutability: "view"
    //     },
    //     {
    //       type: "function",
    //       name: "lockDuration",
    //       inputs: [],
    //       outputs: [
    //         {
    //           name: "",
    //           type: "uint256",
    //           internalType: "uint256"
    //         }
    //       ],
    //       stateMutability: "view"
    //     },
    //     {
    //       type: "function",
    //       name: "owner",
    //       inputs: [],
    //       outputs: [
    //         {
    //           name: "",
    //           type: "address",
    //           internalType: "address"
    //         }
    //       ],
    //       stateMutability: "view"
    //     },
    //     {
    //       type: "function",
    //       name: "proxiableUUID",
    //       inputs: [],
    //       outputs: [
    //         {
    //           name: "",
    //           type: "bytes32",
    //           internalType: "bytes32"
    //         }
    //       ],
    //       stateMutability: "view"
    //     },
    //     {
    //       type: "function",
    //       name: "timeUntilMaturity",
    //       inputs: [],
    //       outputs: [
    //         {
    //           name: "",
    //           type: "uint256",
    //           internalType: "uint256"
    //         }
    //       ],
    //       stateMutability: "view"
    //     },
    //     {
    //       type: "function",
    //       name: "totalDeposited",
    //       inputs: [],
    //       outputs: [
    //         {
    //           name: "",
    //           type: "uint256",
    //           internalType: "uint256"
    //         }
    //       ],
    //       stateMutability: "view"
    //     },
    //     {
    //       type: "function",
    //       name: "updateCid",
    //       inputs: [
    //         {
    //           name: "_depositId",
    //           type: "uint256",
    //           internalType: "uint256"
    //         },
    //         {
    //           name: "_cid",
    //           type: "string",
    //           internalType: "string"
    //         }
    //       ],
    //       outputs: [],
    //       stateMutability: "nonpayable"
    //     },
    //     {
    //       type: "function",
    //       name: "upgradeToAndCall",
    //       inputs: [
    //         {
    //           name: "newImplementation",
    //           type: "address",
    //           internalType: "address"
    //         },
    //         {
    //           name: "data",
    //           type: "bytes",
    //           internalType: "bytes"
    //         }
    //       ],
    //       outputs: [],
    //       stateMutability: "payable"
    //     },
    //     {
    //       type: "function",
    //       name: "usdc",
    //       inputs: [],
    //       outputs: [
    //         {
    //           name: "",
    //           type: "address",
    //           internalType: "contract IERC20"
    //         }
    //       ],
    //       stateMutability: "view"
    //     },
    //     {
    //       type: "function",
    //       name: "vaultName",
    //       inputs: [],
    //       outputs: [
    //         {
    //           name: "",
    //           type: "string",
    //           internalType: "string"
    //         }
    //       ],
    //       stateMutability: "view"
    //     },
    //     {
    //       type: "function",
    //       name: "withdraw",
    //       inputs: [],
    //       outputs: [],
    //       stateMutability: "nonpayable"
    //     },
    //     {
    //       type: "event",
    //       name: "CidUpdated",
    //       inputs: [
    //         {
    //           name: "depositId",
    //           type: "uint256",
    //           indexed: false,
    //           internalType: "uint256"
    //         },
    //         {
    //           name: "cid",
    //           type: "string",
    //           indexed: false,
    //           internalType: "string"
    //         }
    //       ],
    //       anonymous: false
    //     },
    //     {
    //       type: "event",
    //       name: "Deposited",
    //       inputs: [
    //         {
    //           name: "user",
    //           type: "address",
    //           indexed: true,
    //           internalType: "address"
    //         },
    //         {
    //           name: "amount",
    //           type: "uint256",
    //           indexed: false,
    //           internalType: "uint256"
    //         },
    //         {
    //           name: "cid",
    //           type: "string",
    //           indexed: false,
    //           internalType: "string"
    //         },
    //         {
    //           name: "depositId",
    //           type: "uint256",
    //           indexed: false,
    //           internalType: "uint256"
    //         }
    //       ],
    //       anonymous: false
    //     },
    //     {
    //       type: "event",
    //       name: "EarlyWithdrawalAttempt",
    //       inputs: [
    //         {
    //           name: "user",
    //           type: "address",
    //           indexed: true,
    //           internalType: "address"
    //         },
    //         {
    //           name: "attemptedAmount",
    //           type: "uint256",
    //           indexed: false,
    //           internalType: "uint256"
    //         }
    //       ],
    //       anonymous: false
    //     },
    //     {
    //       type: "event",
    //       name: "Initialized",
    //       inputs: [
    //         {
    //           name: "version",
    //           type: "uint64",
    //           indexed: false,
    //           internalType: "uint64"
    //         }
    //       ],
    //       anonymous: false
    //     },
    //     {
    //       type: "event",
    //       name: "Upgraded",
    //       inputs: [
    //         {
    //           name: "implementation",
    //           type: "address",
    //           indexed: true,
    //           internalType: "address"
    //         }
    //       ],
    //       anonymous: false
    //     },
    //     {
    //       type: "event",
    //       name: "VaultInitialized",
    //       inputs: [
    //         {
    //           name: "owner",
    //           type: "address",
    //           indexed: true,
    //           internalType: "address"
    //         },
    //         {
    //           name: "lockDuration",
    //           type: "uint256",
    //           indexed: false,
    //           internalType: "uint256"
    //         },
    //         {
    //           name: "vaultName",
    //           type: "string",
    //           indexed: false,
    //           internalType: "string"
    //         }
    //       ],
    //       anonymous: false
    //     },
    //     {
    //       type: "event",
    //       name: "Withdrawn",
    //       inputs: [
    //         {
    //           name: "user",
    //           type: "address",
    //           indexed: true,
    //           internalType: "address"
    //         },
    //         {
    //           name: "amount",
    //           type: "uint256",
    //           indexed: false,
    //           internalType: "uint256"
    //         }
    //       ],
    //       anonymous: false
    //     },
    //     {
    //       type: "error",
    //       name: "AddressEmptyCode",
    //       inputs: [
    //         {
    //           name: "target",
    //           type: "address",
    //           internalType: "address"
    //         }
    //       ]
    //     },
    //     {
    //       type: "error",
    //       name: "ERC1967InvalidImplementation",
    //       inputs: [
    //         {
    //           name: "implementation",
    //           type: "address",
    //           internalType: "address"
    //         }
    //       ]
    //     },
    //     {
    //       type: "error",
    //       name: "ERC1967NonPayable",
    //       inputs: []
    //     },
    //     {
    //       type: "error",
    //       name: "FailedCall",
    //       inputs: []
    //     },
    //     {
    //       type: "error",
    //       name: "InvalidInitialization",
    //       inputs: []
    //     },
    //     {
    //       type: "error",
    //       name: "NotInitializing",
    //       inputs: []
    //     },
    //     {
    //       type: "error",
    //       name: "ReentrancyGuardReentrantCall",
    //       inputs: []
    //     },
    //     {
    //       type: "error",
    //       name: "SafeERC20FailedOperation",
    //       inputs: [
    //         {
    //           name: "token",
    //           type: "address",
    //           internalType: "address"
    //         }
    //       ]
    //     },
    //     {
    //       type: "error",
    //       name: "UUPSUnauthorizedCallContext",
    //       inputs: []
    //     },
    //     {
    //       type: "error",
    //       name: "UUPSUnsupportedProxiableUUID",
    //       inputs: [
    //         {
    //           name: "slot",
    //           type: "bytes32",
    //           internalType: "bytes32"
    //         }
    //       ]
    //     }
    //   ],
    //   inheritedFunctions: {},
    //   deployedOnBlock: 30661187,
    // },
    PersonalVaultFactory: {
      address: "0x3505776cfb028fec11eb6b67db443c5a502229c0",
      abi: 
      [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "UPGRADE_INTERFACE_VERSION",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "createdAt",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "deposit",
          inputs: [
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "deposit",
          inputs: [
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "_cid",
              type: "string",
              internalType: "string"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "depositCids",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "depositCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "getBalance",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "getCid",
          inputs: [
            {
              name: "_depositId",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "getDepositCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "getLockEndTime",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "initialize",
          inputs: [
            {
              name: "_owner",
              type: "address",
              internalType: "address"
            },
            {
              name: "_lockDuration",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "_usdc",
              type: "address",
              internalType: "address"
            },
            {
              name: "_vaultName",
              type: "string",
              internalType: "string"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "isMature",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "lockDuration",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "proxiableUUID",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "timeUntilMaturity",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "totalDeposited",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "updateCid",
          inputs: [
            {
              name: "_depositId",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "_cid",
              type: "string",
              internalType: "string"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "upgradeToAndCall",
          inputs: [
            {
              name: "newImplementation",
              type: "address",
              internalType: "address"
            },
            {
              name: "data",
              type: "bytes",
              internalType: "bytes"
            }
          ],
          outputs: [],
          stateMutability: "payable"
        },
        {
          type: "function",
          name: "usdc",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "vaultName",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "event",
          name: "CidUpdated",
          inputs: [
            {
              name: "depositId",
              type: "uint256",
              indexed: false,
              internalType: "uint256"
            },
            {
              name: "cid",
              type: "string",
              indexed: false,
              internalType: "string"
            }
          ],
          anonymous: false
        },
        {
          type: "event",
          name: "Deposited",
          inputs: [
            {
              name: "user",
              type: "address",
              indexed: true,
              internalType: "address"
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256"
            },
            {
              name: "cid",
              type: "string",
              indexed: false,
              internalType: "string"
            },
            {
              name: "depositId",
              type: "uint256",
              indexed: false,
              internalType: "uint256"
            }
          ],
          anonymous: false
        },
        {
          type: "event",
          name: "EarlyWithdrawalAttempt",
          inputs: [
            {
              name: "user",
              type: "address",
              indexed: true,
              internalType: "address"
            },
            {
              name: "attemptedAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256"
            }
          ],
          anonymous: false
        },
        {
          type: "event",
          name: "Initialized",
          inputs: [
            {
              name: "version",
              type: "uint64",
              indexed: false,
              internalType: "uint64"
            }
          ],
          anonymous: false
        },
        {
          type: "event",
          name: "Upgraded",
          inputs: [
            {
              name: "implementation",
              type: "address",
              indexed: true,
              internalType: "address"
            }
          ],
          anonymous: false
        },
        {
          type: "event",
          name: "VaultInitialized",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address"
            },
            {
              name: "lockDuration",
              type: "uint256",
              indexed: false,
              internalType: "uint256"
            },
            {
              name: "vaultName",
              type: "string",
              indexed: false,
              internalType: "string"
            }
          ],
          anonymous: false
        },
        {
          type: "event",
          name: "Withdrawn",
          inputs: [
            {
              name: "user",
              type: "address",
              indexed: true,
              internalType: "address"
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256"
            }
          ],
          anonymous: false
        },
        {
          type: "error",
          name: "AddressEmptyCode",
          inputs: [
            {
              name: "target",
              type: "address",
              internalType: "address"
            }
          ]
        },
        {
          type: "error",
          name: "ERC1967InvalidImplementation",
          inputs: [
            {
              name: "implementation",
              type: "address",
              internalType: "address"
            }
          ]
        },
        {
          type: "error",
          name: "ERC1967NonPayable",
          inputs: []
        },
        {
          type: "error",
          name: "FailedCall",
          inputs: []
        },
        {
          type: "error",
          name: "InvalidInitialization",
          inputs: []
        },
        {
          type: "error",
          name: "NotInitializing",
          inputs: []
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: []
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address"
            }
          ]
        },
        {
          type: "error",
          name: "UUPSUnauthorizedCallContext",
          inputs: []
        },
        {
          type: "error",
          name: "UUPSUnsupportedProxiableUUID",
          inputs: [
            {
              name: "slot",
              type: "bytes32",
              internalType: "bytes32"
            }
          ]
        }
      ],
      inheritedFunctions: {},
      deployedOnBlock: 30661187,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
